import type { Metadata } from "next";
import localFont from "next/font/local";
import SkipLink from "./components/SkipLink";
import LanguageProvider from "./components/LanguageProvider";
import "./globals.css";

const flexo = localFont({
  src: [
    {
      path: './font/Flexo-Medium.woff2',
    },
    {
      path: './font/Flexo-Medium.woff',
    }
  ],
  display: 'auto'
})

export const metadata: Metadata = {
  title: "Scarlet/Violet Shiny Hunter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={flexo.className}>
        <LanguageProvider>
          <SkipLink />
          {children}
        </LanguageProvider>
      </body>
    </html>
  );
}
